const obiady = [
  'pierogi z miecem',
  'pierogi z kapustą i grzybami',
    'pierogi ruskie',
  'hot-dog klasyk',
  'wrap z kurczakiem',
  'sałatka cezar',
  'frytki',
  'burger wołowy',
    'burger wegetariański',
    'burger z kurczakiem',

  'pizza mrożona',
  'lasagne bolognese',
'lasagne szpinakowa',
'pene z kurczakiem i brokułami',
'spaghetti bolognese',
'penne carbonara',
'kurczak curry z ryżem',
'kurczak po tajsku',
'kurczak słodko kwaśny',
'kurczak w sosie pieczarkowym',
'klopsiki w sosie pomidorowym',
'pulpeciki w sosie koperkowym',
'kotlety mielone z ziemniakami i surówką',
'pizza pepperoni',
'pizza capriciosa',
'pizza cztery sery',
'pizza margarita',
'gulasz wołowy',
'bigos',
'gołąbki',
'kopytka z sosem pieczarkowym',
'placki ziemniaczane',
'naleśniki z serem',
'naleśniki z jabłkami',

];

const desery = [
  'pudding waniliowy',
  'pudding czekoladowy',
  'pudding karmelowy',
  'budyń śmietankowy',
  'budyń czekoladowy',
  'jogurt stracciatella',
  'jogurt malinowy',
  'jogurt truskawkowy',
  'jogurt brzoskwiniowy',
  'jogurt pitny truskawka',
  'jogurt pitny banan truskawka',
  'kinder bueno',
  'kinder bueno white',
  'kinder country',
  'kinder czekolada',
  'milka oreo',
  'milka truskawkowa',
  'milka karmelowa',
  'twix',
  'snickers',
  'mars',
  'kitkat',
  'princessa kokosowa',
  'princessa orzechowa',
  'grześki',
  'pawełek',
  'michałki',
  'drożdżówka z serem',
  'drożdżówka z budyniem',
  'drożdżówka z jabłkiem',
  'drożdżówka z makiem',
  'ciastko francuskie z jabłkiem',
  'ciastko francuskie z czekoladą',
  'oreo klasyczne',
  'oreo golden',
  'ciastka hit czekolada',
  'ciastka hit wanilia',
  'jeżyki classic',
  'jeżyki kokos',
  'delicje pomarańczowe',
  'delicje malinowe',
  'ciasteczka owsiane',
  'lody kaktus',
  'lody ekipa',
  'lody magnum classic',
  'lody magnum almond',
  'lody cornetto wanilia',
  'lody cornetto truskawka',
  'lody big milk',
  'nutella mała',
  'nutella średnia',
  'nutella na łyżkę',
  'banan premium',
  'jabłko słodkie',
  'gruszka konferencja',
  'milkshake wanilia',
]

const browce = [
  'harnas',
  'harnas czteropak',
  'harnas szesciopak',
  'tyskie',
  'tyskie czteropak',
  'tyskie szesciopak',
  'lech jasny',
  'lech free',
  'lech czteropak',
  'lech szesciopak',
  'zywiec',
  'zywiec czteropak',
  'zywiec szesciopak',
  'perla chmielowa',
  'perla mocna',
  'perla czteropak',
  'perla szesciopak',
  'warka jasna',
  'warka strong',
  'warka czteropak',
  'warka szesciopak',
  'okocim jasne',
  'okocim mocne',
  'okocim czteropak',
  'okocim szesciopak',
  'karpackie',
  'karpackie mocne',
  'karpackie czteropak',
  'karpackie szesciopak',
  'argus',
  'argus strong',
  'argus czteropak',
  'argus szesciopak',
  'karmi',
  'karmi malinowe',
  'karmi orzechowe',
  'somersby jabłko',
  'somersby gruszka',
  'somersby arbuz',
  'somersby czteropak',
  'desperados',
  'desperados lime',
  'desperados red',
  'desperados czteropak',
  'radler cytryna',
  'radler limonka',
  'radler malinowy',
  'radler czteropak',
  'piwo bezalkoholowe 0%',
  'piwo smakowe 0%',
  'cola',
  'cola zero',
  'pepsi',
  'pepsi max',
  'fanta',
  'sprite',
  'mirinda',
  'izotonik niebieski',
];

function losuj(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const startBtn = document.querySelector('#start');

startBtn.addEventListener('click', () => {
  const obiad = losuj(obiady);
  const deser = losuj(desery);
  const picko = losuj(browce);

  document.querySelector('#obiad').textContent = obiad;
  document.querySelector('#deser').textContent = deser;
  document.querySelector('#picko').textContent = picko;
});
